# Generated by Django 5.1.5 on 2025-01-29 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aredwallet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
